### ISSUE TITLE
":" in identifier name

### ISSUE THREAD

**Issue by flexoid** [jamesotron/FlavourSaver#28]
If I understand correctly, according to this http://handlebarsjs.com/expressions.html (search "except for the following" on the page), it should be possible to use **:** (colon) as part of identifier name. We use colons in our templates, and I faced this issue while migrating our server-side handlebars compiling from V8 to FlavourSaver.
BTW, thanks for the great gem!

**Comment by grumbleafrican** [comment]
This is effectively a duplicate of issue  #32 - resolve in favor of that

**Comment by flexoid** [comment]
Thanks, looks like it works now on the version from the master branch. Could you prepare a release?

**Comment by flexoid** [comment]
@grumbleafrican @jamesotron sorry to bother you guys, but could you make a new release with this and some other fixes? The previous one was more that a year ago. I would like to avoid using gem from master branch in production. Thanks in advance.

**Comment by jamesotron** [comment]
Hey. I've added both @flexoid and @grumbleafrican as collaborators for this repo. I'm also happy to add you as gem owners on Rubygems if you let me know your Rubygems email addresses.

**Comment by flexoid** [comment]
@jamesarosen thanks, my profile is https://rubygems.org/profiles/flexoid
I think this issue can be closed.
